config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  # Defines the root path route ("/")
  # root "articles#index"
  resources :types, only: [:category, :search]
  get '/categories/:type_id', to: 'pokemons#category', as: 'category'
  get '/about', to: 'pokemons#about', as: 'about'
  get '/pokemons/search', to: 'pokemons#search', as: 'search_pokemons'
  resources :pokemons, only: [:index, :show, :edit, :update, :destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/pokemon.rb
class Pokemon < ApplicationRecord
    belongs_to :type_id, class_name: 'Type', foreign_key: "type1"
    belongs_to :type_id, class_name: 'Type', foreign_key: "type2", optional: true
    validates :name, :type1, :HP, :ATK, :DEF, :SA, :SD, :SP, presence: true
end

app/models/type.rb
class Type < ApplicationRecord
    has_many :pokemons, class_name: "Pokemon", foreign_key: "type1"
    has_many :pokemons, class_name: "Pokemon", foreign_key: "type2"
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pokemons_controller.rb
class PokemonsController < ApplicationController
    def index
      @pokemons = Pokemon.includes(:type_id).paginate(page: params[:page], per_page: 10)
    end
    def show
      @pokemon = Pokemon.find(params[:id])
    end

    def edit
      @pokemon = Pokemon.find(params[:id])
    end

    def destroy
      @pokemon = Pokemon.find(params[:id])
      @pokemon.destroy
      redirect_to pokemons_path, notice: "Pokemon was successfully deleted."
    end

    def category
      @type = Type.find(params[:type_id])
      @pokemons = Pokemon.where("type1 = ? OR type2 = ?", @type.id, @type.id).paginate(page: params[:page], per_page: 10)
    end  
    
    def search
      keyword = params[:keyword]
      type_id = params[:type_id]
    
      if type_id.present? && type_id.to_i != 0
        @pokemons = Pokemon.where("name LIKE ? AND (type1 = ? OR type2 = ?)", "%#{keyword}%", type_id, type_id)
      else
        @pokemons = Pokemon.where("name LIKE ?", "%#{keyword}%")
      end
    end

    def update
      @pokemon = Pokemon.find(params[:id])
    
      if @pokemon.update(pokemon_params)
        redirect_to @pokemon, notice: "Pokemon was successfully updated."
      else
        flash.now[:alert] = "Failed to update the Pokemon."
        render :edit
      end
    end

    private

    def pokemon_params
      params.require(:pokemon).permit(:name, :HP, :ATK, :DEF, :SA, :SD, :SP)
    end
    
  end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsIntroProject</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-geWF76RCwLtnZ8qwWowPQNguL3RmwHVBC9FhGdlKrxdiJJigb/j/68SIy3Te4Bkz" crossorigin="anonymous"></script>
  </head>

  <body>
    <%= render 'shared/navbar' %>
    <%= yield %>
  </body>
</html>

app/views/pokemons/about.html.erb
<div class="container align-items-center">
  <div class="row">
    <div class="col">
      <h1>About this page:</h1>

      <p class="align-items-center">
        This site contains pokemons from an online API and some of the fake pokemons created by Faker.
        <br>
        The main part of data is coming from:
        <br>
        <a href="https://pokeapi.co/api/v2/pokemon?limit=100000&offset=0">https://pokeapi.co/api/v2/pokemon?limit=100000&offset=0</a>
        <br>
        This API contains pokemon information like:
        <br>
        {"name":"bulbasaur","url":"https://pokeapi.co/api/v2/pokemon/1/"}
        <br>
        It has the name of the pokemon and a link to another API.
        In that link, the API provides all the detailed information of that pokemon.
        <br>
        This site takes the pokemon name from the first API,
        type (might be two), stats (total six), and image URL from the second API.
        <br>
        To put into the database, there are two tables:
        <br>
        One for pokemon (id[pk], name, type1[fk], type2[fk], hp, atk, def, sa, sd, sp, img),
        <br>
        One for type (id[pk], name).
      </p>
      <img src="<%= asset_path("railsIntroERD.jpg") %>", alt="ERD">
    </div>
  </div>
</div>

app/views/pokemons/category.html.erb
<h1>Pokemons - <%= @type.name.capitalize %> Type</h1>

<div class="container">
  <table class="table table-bordered">
    <thead>
      <tr class="d-flex align-items-center">
        <th class="flex-grow-1">ID</th>
        <th class="flex-grow-1">Image</th>
        <th class="flex-grow-1">Name</th>
      </tr>
    </thead>
    <tbody>
      <% @pokemons.each do |pokemon| %>
        <tr class="d-flex align-items-center">
          <td class="flex-grow-1"><%= pokemon.id %></td>
          <td class="flex-grow-1">
            <div class="d-flex justify-content-center">
              <div class="crop">
                <%= link_to pokemon_path(pokemon) do %>
                  <%= image_tag pokemon.image, class: "img-fluid", style: "width: 100px; height: 100px;", alt: "image" %>
                <% end %>
              </div>
            </div>
          </td>
          <td class="flex-grow-1"><%= link_to pokemon.name, pokemon_path(pokemon) %><% if pokemon.HP + pokemon.ATK + pokemon.DEF + pokemon.SA + pokemon.SD + pokemon.SP > 550 %> (Stronk)<% end %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

<nav class="float-right mt-2">
  <ul class="pagination pagination-sm">
    <% if @pokemons.previous_page %>
      <li class="page-item">
        <%= link_to 'Previous', category_path(@type, page: @pokemons.previous_page), class: 'page-link' %>
      </li>
    <% end %>

    <% if @pokemons.next_page %>
      <li class="page-item">
        <%= link_to 'Next', category_path(@type, page: @pokemons.next_page), class: 'page-link' %>
      </li>
    <% end %>
  </ul>
</nav>

app/views/pokemons/edit.html.erb
<h1>Edit Pokemon</h1>

<%= form_with(model: @pokemon, url: pokemon_path(@pokemon), method: :patch) do |form| %>
  
  <div class="form-group">
    <%= form.label :name %>
    <%= form.text_field :name, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :HP %>
    <%= form.number_field :HP, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :ATK %>
    <%= form.number_field :ATK, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :DEF %>
    <%= form.number_field :DEF, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :SA %>
    <%= form.number_field :SA, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :SD %>
    <%= form.number_field :SD, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :SP %>
    <%= form.number_field :SP, class: 'form-control' %>
  </div>

  <%= form.submit 'Update', class: 'btn btn-primary' %>
<% end %>

app/views/pokemons/index.html.erb
<h1>Pokemons</h1>

<div class="container">
  <% if @pokemons.any? %>
    <table class="table table-bordered">
      <thead>
        <tr class="d-flex align-items-center">
          <th class="flex-grow-1">ID</th>
          <th class="flex-grow-1">Image</th>
          <th class="flex-grow-1">Name</th>
        </tr>
      </thead>
      <tbody>
        <% @pokemons.each do |pokemon| %>
          <tr class="d-flex align-items-center">
            <td class="flex-grow-1"><%= pokemon.id %></td>
            <td class="flex-grow-1">
              <div class="d-flex justify-content-center">
                <div class="crop">
                  <%= link_to pokemon_path(pokemon) do %>
                    <%= image_tag pokemon.image, class: "img-fluid", style: "width: 100px; height: 100px;", alt: "Image" %>
                  <% end %>
                </div>
              </div>
            </td>
            <td class="flex-grow-1"><%= link_to pokemon.name, pokemon_path(pokemon) %><% if pokemon.HP + pokemon.ATK + pokemon.DEF + pokemon.SA + pokemon.SD + pokemon.SP > 550 %> (Stronk)<% end %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  <% else %>
    <p>No Pokemons here</p>
  <% end %>
</div>

<nav class="float-right mt-2">
  <ul class="pagination pagination-sm">
    <% if @pokemons.previous_page %>
      <li class="page-item">
        <%= link_to 'Previous', pokemons_path(page: @pokemons.previous_page), class: 'page-link' %>
      </li>
    <% end %>

    <% if @pokemons.next_page %>
      <li class="page-item">
        <%= link_to 'Next', pokemons_path(page: @pokemons.next_page), class: 'page-link' %>
      </li>
    <% end %>
  </ul>
</nav>


app/views/pokemons/search.html.erb
<h1>Pokemon Search</h1>

<div class="container">
  <h3>Search Results</h3>

  <% if @pokemons.any? %>
    <table class="table table-bordered">
      <thead>
        <tr class="d-flex align-items-center">
          <th class="flex-grow-1">ID</th>
          <th class="flex-grow-1">Image</th>
          <th class="flex-grow-1">Name</th>
        </tr>
      </thead>
      <tbody>
        <% @pokemons.each do |pokemon| %>
          <tr class="d-flex align-items-center">
            <td class="flex-grow-1"><%= pokemon.id %></td>
            <td class="flex-grow-1">
              <div class="d-flex justify-content-center">
                <div class="crop">
                  <%= link_to pokemon_path(pokemon) do %>
                    <%= image_tag pokemon.image, class: "img-fluid", style: "width: 100px; height: 100px;", alt: "image" %>
                  <% end %>
                </div>
              </div>
            </td>
            <td class="flex-grow-1"><%= link_to pokemon.name, pokemon_path(pokemon) %><% if pokemon.HP + pokemon.ATK + pokemon.DEF + pokemon.SA + pokemon.SD + pokemon.SP > 550 %> (Stronk)<% end %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  <% else %>
    <p>No results found.</p>
  <% end %>
</div>

app/views/pokemons/show.html.erb
<div class="row">
  <div class="col-md-6 d-flex flex-column align-items-end">
    <h1><%= @pokemon.name %></h1>
    <p>ID: <%= @pokemon.id %></p>
    <img src="<%= @pokemon.image %>" alt="Image">
  </div>
  <div class="col-md-6">
    <div class="d-flex flex-column">
      <h2>Type</h2>
        <p>Type 1: <%= link_to Type.find_by(id: @pokemon.type1)&.name, category_path(@pokemon.type1) %></p>
      <% if @pokemon.type2.present? %>
        <p>Type 2: <%= link_to Type.find_by(id: @pokemon.type2)&.name, category_path(@pokemon.type2) %></p>
      <% end %>

      <h2>Stats</h2>
      <p>HP: <%= @pokemon.HP %><% if @pokemon.HP > 100 %> *<% end %></p>
      <p>Attack: <%= @pokemon.ATK %><% if @pokemon.ATK > 100 %> *<% end %></p>
      <p>Defense: <%= @pokemon.DEF %><% if @pokemon.DEF > 100 %> *<% end %></p>
      <p>Special Attack: <%= @pokemon.SA %><% if @pokemon.SA > 100 %> *<% end %></p>
      <p>Special Defense: <%= @pokemon.SD %><% if @pokemon.SD > 100 %> *<% end %></p>
      <p>Speed: <%= @pokemon.SP %><% if @pokemon.SP > 100 %> *<% end %></p>
      <p>Total: <%= @pokemon.HP + @pokemon.ATK + @pokemon.DEF + @pokemon.SA + @pokemon.SD + @pokemon.SP %><% if @pokemon.HP + @pokemon.ATK + @pokemon.DEF + @pokemon.SA + @pokemon.SD + @pokemon.SP > 550 %> *<% end %></p>

      <div class="d-flex">
        <%= link_to 'Edit', edit_pokemon_path(@pokemon.id), class: 'btn btn-primary mr-2' %>
        <%= link_to 'Delete', pokemon_path(@pokemon), method: :delete, class: 'btn btn-danger' %>
      </div>
    </div>
  </div>
</div>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-xl navbar-dark bg-dark">
    <div class="flex-grow-1 navbar-collapse">
        <a class="navbar-brand" href="/pokemons">Pokemon</a>

        <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
                <a class="nav-link" href="/about">About</a>
            </li>
        </ul>
    </div>

    <div class="flex-grow-2 navbar-collapse justify-content-end">

        <form class="form-inline mt-2 mt-md-0 justify-content-end" action="/pokemons/search" accept-charset="UTF-8" method="get">
            <div class="d-flex align-items-center ml-auto">
            <div class="flex-grow-1">
                <input type="text" name="keyword" id="keyword" class="form-control" placeholder="Game Search" />
            </div>
            <div class="flex-grow-1">
                <select name="type_id" id="type_id" class="form-control">
                <option value="0">All</option>
                <% Type.all.each do |type| %>
                    <option value="<%= type.id %>"><%= type.name %></option>
                <% end %>
                </select>
            </div>
            <div class="flex-grow-1">
                <input type="submit" name="commit" value="Search" class="btn btn-outline-success" data-disable-with="Search" />
            </div>
            </div>
        </form>
    </div>
</nav>